---
- hosts: build-slave
  become: true
  tasks:
    - name: Update ubuntu repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Install java
      apt:
        name: openjdk-11-jre
        state: present

    - name: Download maven packages
      get_url:
        url: https://dlcdn.apache.org/maven/maven-3/3.9.7/binaries/apache-maven-3.9.7-bin.tar.gz
        dest: /opt

    - name: Extract maven
      unarchive:
        src: /opt/apache-maven-3.9.7-bin.tar.gz
        dest: /opt
        remote_src: yes
